// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotServiceProto.proto

package com.ncirl.streaming.streamingclientservice;

public interface QuantityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.streaming.QuantityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productId = 1;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string productId = 1;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();
}
