// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotServiceProto.proto

package com.ncirl.streaming.streamingclientservice;

public interface QuantityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.streaming.QuantityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 quantity = 1;</code>
   * @return The quantity.
   */
  int getQuantity();
}
