// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotServiceProto.proto

package com.ncirl.streaming.streamingclientservice;

public final class RobotServiceProto {
  private RobotServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_UnaryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_UnaryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_UnaryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_UnaryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_ClientInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_ClientInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_ServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_ServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_QuantityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_QuantityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_QuantityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_QuantityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027RobotServiceProto.proto\022\023com.ncirl.str" +
      "eaming\"\034\n\014UnaryRequest\022\014\n\004name\030\001 \001(\t\" \n\r" +
      "UnaryResponse\022\017\n\007message\030\001 \001(\t\"9\n\021Client" +
      "Information\022\022\n\nclientName\030\001 \001(\t\022\020\n\010dateT" +
      "ime\030\002 \001(\t\"!\n\016ServerResponse\022\017\n\007message\030\001" +
      " \001(\t\"$\n\017QuantityRequest\022\021\n\tproductId\030\001 \001" +
      "(\t\"$\n\020QuantityResponse\022\020\n\010quantity\030\001 \001(\005" +
      "2\302\002\n\026StreamingClientService\022Y\n\020sendUnary" +
      "Request\022!.com.ncirl.streaming.UnaryReque" +
      "st\032\".com.ncirl.streaming.UnaryResponse\022c" +
      "\n\024getWarehouseQuantity\022$.com.ncirl.strea" +
      "ming.QuantityRequest\032%.com.ncirl.streami" +
      "ng.QuantityResponse\022h\n\027streamClientInfor" +
      "mation\022&.com.ncirl.streaming.ClientInfor" +
      "mation\032#.com.ncirl.streaming.ServerRespo" +
      "nse(\001BA\n*com.ncirl.streaming.streamingcl" +
      "ientserviceB\021RobotServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ncirl_streaming_UnaryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ncirl_streaming_UnaryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_UnaryRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_ncirl_streaming_UnaryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ncirl_streaming_UnaryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_UnaryResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_ncirl_streaming_ClientInformation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ncirl_streaming_ClientInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_ClientInformation_descriptor,
        new java.lang.String[] { "ClientName", "DateTime", });
    internal_static_com_ncirl_streaming_ServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ncirl_streaming_ServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_ServerResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_ncirl_streaming_QuantityRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_ncirl_streaming_QuantityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_QuantityRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_com_ncirl_streaming_QuantityResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_ncirl_streaming_QuantityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_QuantityResponse_descriptor,
        new java.lang.String[] { "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
