// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotServiceProto.proto

package com.ncirl.robotics.robot;

public interface InventoryCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.robotics.InventoryCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The response can include details such as item count, item conditions, etc.
   * </pre>
   *
   * <code>int32 item_count = 1;</code>
   * @return The itemCount.
   */
  int getItemCount();

  /**
   * <code>string condition = 2;</code>
   * @return The condition.
   */
  java.lang.String getCondition();
  /**
   * <code>string condition = 2;</code>
   * @return The bytes for condition.
   */
  com.google.protobuf.ByteString
      getConditionBytes();

  /**
   * <code>bool is_restock_needed = 3;</code>
   * @return The isRestockNeeded.
   */
  boolean getIsRestockNeeded();
}
