// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotServiceProto.proto

package com.ncirl.robotics.robot;

public interface InventoryCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.robotics.InventoryCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * We can include specifics like aisle, shelf, or product ID
   * </pre>
   *
   * <code>string aisle = 1;</code>
   * @return The aisle.
   */
  java.lang.String getAisle();
  /**
   * <pre>
   * We can include specifics like aisle, shelf, or product ID
   * </pre>
   *
   * <code>string aisle = 1;</code>
   * @return The bytes for aisle.
   */
  com.google.protobuf.ByteString
      getAisleBytes();

  /**
   * <code>string shelf = 2;</code>
   * @return The shelf.
   */
  java.lang.String getShelf();
  /**
   * <code>string shelf = 2;</code>
   * @return The bytes for shelf.
   */
  com.google.protobuf.ByteString
      getShelfBytes();

  /**
   * <code>string product_id = 3;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 3;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();
}
