// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotServiceProto.proto

package com.ncirl.robotics.robot;

public interface InventoryMonitorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.robotics.InventoryMonitorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Similar specifics can be included if needed
   * </pre>
   *
   * <code>string area = 1;</code>
   * @return The area.
   */
  java.lang.String getArea();
  /**
   * <pre>
   * Similar specifics can be included if needed
   * </pre>
   *
   * <code>string area = 1;</code>
   * @return The bytes for area.
   */
  com.google.protobuf.ByteString
      getAreaBytes();
}
