// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotServiceProto.proto

package com.ncirl.robotics.robot;

public interface InventoryMonitorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.robotics.InventoryMonitorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Details about the monitored inventory over time
   * </pre>
   *
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * Details about the monitored inventory over time
   * </pre>
   *
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 items_scanned = 2;</code>
   * @return The itemsScanned.
   */
  int getItemsScanned();

  /**
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
