// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotServiceProto.proto

package com.ncirl.robotics.robot;

/**
 * <pre>
 * Request message for checking the inventory
 * </pre>
 *
 * Protobuf type {@code com.ncirl.robotics.InventoryCheckRequest}
 */
public final class InventoryCheckRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ncirl.robotics.InventoryCheckRequest)
    InventoryCheckRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InventoryCheckRequest.newBuilder() to construct.
  private InventoryCheckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InventoryCheckRequest() {
    aisle_ = "";
    shelf_ = "";
    productId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InventoryCheckRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InventoryCheckRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            aisle_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            shelf_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            productId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ncirl.robotics.robot.RobotServiceProto.internal_static_com_ncirl_robotics_InventoryCheckRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ncirl.robotics.robot.RobotServiceProto.internal_static_com_ncirl_robotics_InventoryCheckRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ncirl.robotics.robot.InventoryCheckRequest.class, com.ncirl.robotics.robot.InventoryCheckRequest.Builder.class);
  }

  public static final int AISLE_FIELD_NUMBER = 1;
  private volatile java.lang.Object aisle_;
  /**
   * <pre>
   * We can include specifics like aisle, shelf, or product ID
   * </pre>
   *
   * <code>string aisle = 1;</code>
   * @return The aisle.
   */
  @java.lang.Override
  public java.lang.String getAisle() {
    java.lang.Object ref = aisle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aisle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * We can include specifics like aisle, shelf, or product ID
   * </pre>
   *
   * <code>string aisle = 1;</code>
   * @return The bytes for aisle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAisleBytes() {
    java.lang.Object ref = aisle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aisle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHELF_FIELD_NUMBER = 2;
  private volatile java.lang.Object shelf_;
  /**
   * <code>string shelf = 2;</code>
   * @return The shelf.
   */
  @java.lang.Override
  public java.lang.String getShelf() {
    java.lang.Object ref = shelf_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shelf_ = s;
      return s;
    }
  }
  /**
   * <code>string shelf = 2;</code>
   * @return The bytes for shelf.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getShelfBytes() {
    java.lang.Object ref = shelf_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shelf_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCT_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object productId_;
  /**
   * <code>string product_id = 3;</code>
   * @return The productId.
   */
  @java.lang.Override
  public java.lang.String getProductId() {
    java.lang.Object ref = productId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productId_ = s;
      return s;
    }
  }
  /**
   * <code>string product_id = 3;</code>
   * @return The bytes for productId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductIdBytes() {
    java.lang.Object ref = productId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(aisle_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aisle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shelf_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, shelf_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(aisle_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aisle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shelf_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, shelf_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ncirl.robotics.robot.InventoryCheckRequest)) {
      return super.equals(obj);
    }
    com.ncirl.robotics.robot.InventoryCheckRequest other = (com.ncirl.robotics.robot.InventoryCheckRequest) obj;

    if (!getAisle()
        .equals(other.getAisle())) return false;
    if (!getShelf()
        .equals(other.getShelf())) return false;
    if (!getProductId()
        .equals(other.getProductId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AISLE_FIELD_NUMBER;
    hash = (53 * hash) + getAisle().hashCode();
    hash = (37 * hash) + SHELF_FIELD_NUMBER;
    hash = (53 * hash) + getShelf().hashCode();
    hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProductId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ncirl.robotics.robot.InventoryCheckRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.robotics.robot.InventoryCheckRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.robotics.robot.InventoryCheckRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.robotics.robot.InventoryCheckRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.robotics.robot.InventoryCheckRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.robotics.robot.InventoryCheckRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.robotics.robot.InventoryCheckRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.robotics.robot.InventoryCheckRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.robotics.robot.InventoryCheckRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ncirl.robotics.robot.InventoryCheckRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.robotics.robot.InventoryCheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.robotics.robot.InventoryCheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ncirl.robotics.robot.InventoryCheckRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for checking the inventory
   * </pre>
   *
   * Protobuf type {@code com.ncirl.robotics.InventoryCheckRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ncirl.robotics.InventoryCheckRequest)
      com.ncirl.robotics.robot.InventoryCheckRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ncirl.robotics.robot.RobotServiceProto.internal_static_com_ncirl_robotics_InventoryCheckRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ncirl.robotics.robot.RobotServiceProto.internal_static_com_ncirl_robotics_InventoryCheckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ncirl.robotics.robot.InventoryCheckRequest.class, com.ncirl.robotics.robot.InventoryCheckRequest.Builder.class);
    }

    // Construct using com.ncirl.robotics.robot.InventoryCheckRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      aisle_ = "";

      shelf_ = "";

      productId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ncirl.robotics.robot.RobotServiceProto.internal_static_com_ncirl_robotics_InventoryCheckRequest_descriptor;
    }

    @java.lang.Override
    public com.ncirl.robotics.robot.InventoryCheckRequest getDefaultInstanceForType() {
      return com.ncirl.robotics.robot.InventoryCheckRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ncirl.robotics.robot.InventoryCheckRequest build() {
      com.ncirl.robotics.robot.InventoryCheckRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ncirl.robotics.robot.InventoryCheckRequest buildPartial() {
      com.ncirl.robotics.robot.InventoryCheckRequest result = new com.ncirl.robotics.robot.InventoryCheckRequest(this);
      result.aisle_ = aisle_;
      result.shelf_ = shelf_;
      result.productId_ = productId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ncirl.robotics.robot.InventoryCheckRequest) {
        return mergeFrom((com.ncirl.robotics.robot.InventoryCheckRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ncirl.robotics.robot.InventoryCheckRequest other) {
      if (other == com.ncirl.robotics.robot.InventoryCheckRequest.getDefaultInstance()) return this;
      if (!other.getAisle().isEmpty()) {
        aisle_ = other.aisle_;
        onChanged();
      }
      if (!other.getShelf().isEmpty()) {
        shelf_ = other.shelf_;
        onChanged();
      }
      if (!other.getProductId().isEmpty()) {
        productId_ = other.productId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ncirl.robotics.robot.InventoryCheckRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ncirl.robotics.robot.InventoryCheckRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object aisle_ = "";
    /**
     * <pre>
     * We can include specifics like aisle, shelf, or product ID
     * </pre>
     *
     * <code>string aisle = 1;</code>
     * @return The aisle.
     */
    public java.lang.String getAisle() {
      java.lang.Object ref = aisle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aisle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * We can include specifics like aisle, shelf, or product ID
     * </pre>
     *
     * <code>string aisle = 1;</code>
     * @return The bytes for aisle.
     */
    public com.google.protobuf.ByteString
        getAisleBytes() {
      java.lang.Object ref = aisle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aisle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * We can include specifics like aisle, shelf, or product ID
     * </pre>
     *
     * <code>string aisle = 1;</code>
     * @param value The aisle to set.
     * @return This builder for chaining.
     */
    public Builder setAisle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aisle_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * We can include specifics like aisle, shelf, or product ID
     * </pre>
     *
     * <code>string aisle = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAisle() {
      
      aisle_ = getDefaultInstance().getAisle();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * We can include specifics like aisle, shelf, or product ID
     * </pre>
     *
     * <code>string aisle = 1;</code>
     * @param value The bytes for aisle to set.
     * @return This builder for chaining.
     */
    public Builder setAisleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aisle_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object shelf_ = "";
    /**
     * <code>string shelf = 2;</code>
     * @return The shelf.
     */
    public java.lang.String getShelf() {
      java.lang.Object ref = shelf_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shelf_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string shelf = 2;</code>
     * @return The bytes for shelf.
     */
    public com.google.protobuf.ByteString
        getShelfBytes() {
      java.lang.Object ref = shelf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shelf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string shelf = 2;</code>
     * @param value The shelf to set.
     * @return This builder for chaining.
     */
    public Builder setShelf(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      shelf_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string shelf = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearShelf() {
      
      shelf_ = getDefaultInstance().getShelf();
      onChanged();
      return this;
    }
    /**
     * <code>string shelf = 2;</code>
     * @param value The bytes for shelf to set.
     * @return This builder for chaining.
     */
    public Builder setShelfBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      shelf_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productId_ = "";
    /**
     * <code>string product_id = 3;</code>
     * @return The productId.
     */
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string product_id = 3;</code>
     * @return The bytes for productId.
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string product_id = 3;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string product_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      
      productId_ = getDefaultInstance().getProductId();
      onChanged();
      return this;
    }
    /**
     * <code>string product_id = 3;</code>
     * @param value The bytes for productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ncirl.robotics.InventoryCheckRequest)
  }

  // @@protoc_insertion_point(class_scope:com.ncirl.robotics.InventoryCheckRequest)
  private static final com.ncirl.robotics.robot.InventoryCheckRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ncirl.robotics.robot.InventoryCheckRequest();
  }

  public static com.ncirl.robotics.robot.InventoryCheckRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InventoryCheckRequest>
      PARSER = new com.google.protobuf.AbstractParser<InventoryCheckRequest>() {
    @java.lang.Override
    public InventoryCheckRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InventoryCheckRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InventoryCheckRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InventoryCheckRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ncirl.robotics.robot.InventoryCheckRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

