// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotServiceProto.proto

package com.ncirl.robotics.robot;

/**
 * <pre>
 * Response message for a stock check
 * </pre>
 *
 * Protobuf type {@code com.ncirl.robotics.InventoryCheckResponse}
 */
public final class InventoryCheckResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ncirl.robotics.InventoryCheckResponse)
    InventoryCheckResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InventoryCheckResponse.newBuilder() to construct.
  private InventoryCheckResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InventoryCheckResponse() {
    condition_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InventoryCheckResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InventoryCheckResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            itemCount_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            condition_ = s;
            break;
          }
          case 24: {

            isRestockNeeded_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ncirl.robotics.robot.RobotServiceProto.internal_static_com_ncirl_robotics_InventoryCheckResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ncirl.robotics.robot.RobotServiceProto.internal_static_com_ncirl_robotics_InventoryCheckResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ncirl.robotics.robot.InventoryCheckResponse.class, com.ncirl.robotics.robot.InventoryCheckResponse.Builder.class);
  }

  public static final int ITEM_COUNT_FIELD_NUMBER = 1;
  private int itemCount_;
  /**
   * <pre>
   * The response can include details such as item count, item conditions, etc.
   * </pre>
   *
   * <code>int32 item_count = 1;</code>
   * @return The itemCount.
   */
  @java.lang.Override
  public int getItemCount() {
    return itemCount_;
  }

  public static final int CONDITION_FIELD_NUMBER = 2;
  private volatile java.lang.Object condition_;
  /**
   * <code>string condition = 2;</code>
   * @return The condition.
   */
  @java.lang.Override
  public java.lang.String getCondition() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      condition_ = s;
      return s;
    }
  }
  /**
   * <code>string condition = 2;</code>
   * @return The bytes for condition.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConditionBytes() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      condition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_RESTOCK_NEEDED_FIELD_NUMBER = 3;
  private boolean isRestockNeeded_;
  /**
   * <code>bool is_restock_needed = 3;</code>
   * @return The isRestockNeeded.
   */
  @java.lang.Override
  public boolean getIsRestockNeeded() {
    return isRestockNeeded_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (itemCount_ != 0) {
      output.writeInt32(1, itemCount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(condition_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, condition_);
    }
    if (isRestockNeeded_ != false) {
      output.writeBool(3, isRestockNeeded_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (itemCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, itemCount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(condition_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, condition_);
    }
    if (isRestockNeeded_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isRestockNeeded_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ncirl.robotics.robot.InventoryCheckResponse)) {
      return super.equals(obj);
    }
    com.ncirl.robotics.robot.InventoryCheckResponse other = (com.ncirl.robotics.robot.InventoryCheckResponse) obj;

    if (getItemCount()
        != other.getItemCount()) return false;
    if (!getCondition()
        .equals(other.getCondition())) return false;
    if (getIsRestockNeeded()
        != other.getIsRestockNeeded()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ITEM_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getItemCount();
    hash = (37 * hash) + CONDITION_FIELD_NUMBER;
    hash = (53 * hash) + getCondition().hashCode();
    hash = (37 * hash) + IS_RESTOCK_NEEDED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsRestockNeeded());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ncirl.robotics.robot.InventoryCheckResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.robotics.robot.InventoryCheckResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.robotics.robot.InventoryCheckResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.robotics.robot.InventoryCheckResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.robotics.robot.InventoryCheckResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.robotics.robot.InventoryCheckResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.robotics.robot.InventoryCheckResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.robotics.robot.InventoryCheckResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.robotics.robot.InventoryCheckResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ncirl.robotics.robot.InventoryCheckResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.robotics.robot.InventoryCheckResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.robotics.robot.InventoryCheckResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ncirl.robotics.robot.InventoryCheckResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response message for a stock check
   * </pre>
   *
   * Protobuf type {@code com.ncirl.robotics.InventoryCheckResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ncirl.robotics.InventoryCheckResponse)
      com.ncirl.robotics.robot.InventoryCheckResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ncirl.robotics.robot.RobotServiceProto.internal_static_com_ncirl_robotics_InventoryCheckResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ncirl.robotics.robot.RobotServiceProto.internal_static_com_ncirl_robotics_InventoryCheckResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ncirl.robotics.robot.InventoryCheckResponse.class, com.ncirl.robotics.robot.InventoryCheckResponse.Builder.class);
    }

    // Construct using com.ncirl.robotics.robot.InventoryCheckResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      itemCount_ = 0;

      condition_ = "";

      isRestockNeeded_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ncirl.robotics.robot.RobotServiceProto.internal_static_com_ncirl_robotics_InventoryCheckResponse_descriptor;
    }

    @java.lang.Override
    public com.ncirl.robotics.robot.InventoryCheckResponse getDefaultInstanceForType() {
      return com.ncirl.robotics.robot.InventoryCheckResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ncirl.robotics.robot.InventoryCheckResponse build() {
      com.ncirl.robotics.robot.InventoryCheckResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ncirl.robotics.robot.InventoryCheckResponse buildPartial() {
      com.ncirl.robotics.robot.InventoryCheckResponse result = new com.ncirl.robotics.robot.InventoryCheckResponse(this);
      result.itemCount_ = itemCount_;
      result.condition_ = condition_;
      result.isRestockNeeded_ = isRestockNeeded_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ncirl.robotics.robot.InventoryCheckResponse) {
        return mergeFrom((com.ncirl.robotics.robot.InventoryCheckResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ncirl.robotics.robot.InventoryCheckResponse other) {
      if (other == com.ncirl.robotics.robot.InventoryCheckResponse.getDefaultInstance()) return this;
      if (other.getItemCount() != 0) {
        setItemCount(other.getItemCount());
      }
      if (!other.getCondition().isEmpty()) {
        condition_ = other.condition_;
        onChanged();
      }
      if (other.getIsRestockNeeded() != false) {
        setIsRestockNeeded(other.getIsRestockNeeded());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ncirl.robotics.robot.InventoryCheckResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ncirl.robotics.robot.InventoryCheckResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int itemCount_ ;
    /**
     * <pre>
     * The response can include details such as item count, item conditions, etc.
     * </pre>
     *
     * <code>int32 item_count = 1;</code>
     * @return The itemCount.
     */
    @java.lang.Override
    public int getItemCount() {
      return itemCount_;
    }
    /**
     * <pre>
     * The response can include details such as item count, item conditions, etc.
     * </pre>
     *
     * <code>int32 item_count = 1;</code>
     * @param value The itemCount to set.
     * @return This builder for chaining.
     */
    public Builder setItemCount(int value) {
      
      itemCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The response can include details such as item count, item conditions, etc.
     * </pre>
     *
     * <code>int32 item_count = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemCount() {
      
      itemCount_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object condition_ = "";
    /**
     * <code>string condition = 2;</code>
     * @return The condition.
     */
    public java.lang.String getCondition() {
      java.lang.Object ref = condition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        condition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string condition = 2;</code>
     * @return The bytes for condition.
     */
    public com.google.protobuf.ByteString
        getConditionBytes() {
      java.lang.Object ref = condition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        condition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string condition = 2;</code>
     * @param value The condition to set.
     * @return This builder for chaining.
     */
    public Builder setCondition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      condition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string condition = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCondition() {
      
      condition_ = getDefaultInstance().getCondition();
      onChanged();
      return this;
    }
    /**
     * <code>string condition = 2;</code>
     * @param value The bytes for condition to set.
     * @return This builder for chaining.
     */
    public Builder setConditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      condition_ = value;
      onChanged();
      return this;
    }

    private boolean isRestockNeeded_ ;
    /**
     * <code>bool is_restock_needed = 3;</code>
     * @return The isRestockNeeded.
     */
    @java.lang.Override
    public boolean getIsRestockNeeded() {
      return isRestockNeeded_;
    }
    /**
     * <code>bool is_restock_needed = 3;</code>
     * @param value The isRestockNeeded to set.
     * @return This builder for chaining.
     */
    public Builder setIsRestockNeeded(boolean value) {
      
      isRestockNeeded_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_restock_needed = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsRestockNeeded() {
      
      isRestockNeeded_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ncirl.robotics.InventoryCheckResponse)
  }

  // @@protoc_insertion_point(class_scope:com.ncirl.robotics.InventoryCheckResponse)
  private static final com.ncirl.robotics.robot.InventoryCheckResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ncirl.robotics.robot.InventoryCheckResponse();
  }

  public static com.ncirl.robotics.robot.InventoryCheckResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InventoryCheckResponse>
      PARSER = new com.google.protobuf.AbstractParser<InventoryCheckResponse>() {
    @java.lang.Override
    public InventoryCheckResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InventoryCheckResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InventoryCheckResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InventoryCheckResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ncirl.robotics.robot.InventoryCheckResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

