// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotServiceProto.proto

package com.ncirl.robotics.robot;

public final class RobotServiceProto {
  private RobotServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_robotics_InventoryCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_robotics_InventoryCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_robotics_InventoryCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_robotics_InventoryCheckResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_robotics_InventoryMonitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_robotics_InventoryMonitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_robotics_InventoryMonitorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_robotics_InventoryMonitorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027RobotServiceProto.proto\022\022com.ncirl.rob" +
      "otics\"I\n\025InventoryCheckRequest\022\r\n\005aisle\030" +
      "\001 \001(\t\022\r\n\005shelf\030\002 \001(\t\022\022\n\nproduct_id\030\003 \001(\t" +
      "\"Z\n\026InventoryCheckResponse\022\022\n\nitem_count" +
      "\030\001 \001(\005\022\021\n\tcondition\030\002 \001(\t\022\031\n\021is_restock_" +
      "needed\030\003 \001(\010\"\'\n\027InventoryMonitorRequest\022" +
      "\014\n\004area\030\001 \001(\t\"T\n\030InventoryMonitorRespons" +
      "e\022\016\n\006status\030\001 \001(\t\022\025\n\ritems_scanned\030\002 \001(\005" +
      "\022\021\n\ttimestamp\030\003 \001(\t2\355\001\n\021SmartRobotServic" +
      "e\022g\n\016CheckInventory\022).com.ncirl.robotics" +
      ".InventoryCheckRequest\032*.com.ncirl.robot" +
      "ics.InventoryCheckResponse\022o\n\020MonitorInv" +
      "entory\022+.com.ncirl.robotics.InventoryMon" +
      "itorRequest\032,.com.ncirl.robotics.Invento" +
      "ryMonitorResponse0\001B/\n\030com.ncirl.robotic" +
      "s.robotB\021RobotServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ncirl_robotics_InventoryCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ncirl_robotics_InventoryCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_robotics_InventoryCheckRequest_descriptor,
        new java.lang.String[] { "Aisle", "Shelf", "ProductId", });
    internal_static_com_ncirl_robotics_InventoryCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ncirl_robotics_InventoryCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_robotics_InventoryCheckResponse_descriptor,
        new java.lang.String[] { "ItemCount", "Condition", "IsRestockNeeded", });
    internal_static_com_ncirl_robotics_InventoryMonitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ncirl_robotics_InventoryMonitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_robotics_InventoryMonitorRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_com_ncirl_robotics_InventoryMonitorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ncirl_robotics_InventoryMonitorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_robotics_InventoryMonitorResponse_descriptor,
        new java.lang.String[] { "Status", "ItemsScanned", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
